name: Publish Package

on:
  push:
    branches: [ main ]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@HENNGE'

      - run: pnpm install --frozen-lockfile

      - name: Create Release PR or Publish
        id: changesets
        uses: changeset/action@v1
        with:
          # This command runs if no changesets are present (it publishes)
          publish: pnpm changeset publish
          # This command runs to bump versions and update changelog
          version: pnpm changeset version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
