name: Check code and test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - name: Restore Packages
        run: pnpm i --frozen-lockfile
      - name: Lint
        run: pnpm lint
      - name: Test
        run: pnpm test
